In [139]:
import numpy as np

In [140]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [141]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [142]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [143]:
a_centered_sp = 0
for i in range(0,np.shape(a_centered)[0]):  a_centered_sp += np.prod(a_centered[i])
a_centered_sp

8.0

In [144]:
N = np.shape(a_centered)[0]
a_centered_sp/(N-1)

2.0

In [145]:
import pandas as pd

In [146]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [147]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]}, columns=['author_id','book_title','price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [148]:
authors_price = pd.merge(authors, book, on = 'author_id', how ='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [149]:
authors_price.nlargest(5, 'price')

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [151]:
authors_min = authors_price.groupby('author_name').agg({'price':'min'})
authors_min = authors_min.reset_index()
authors_min = authors_min.rename(columns={'price':'min_price'})

authors_max = authors_price.groupby('author_name').agg({'price':'max'})
authors_max = authors_max.reset_index()
authors_max = authors_max.rename(columns={'price':'max_price'})

authors_mean = authors_price.groupby('author_name').agg({'price':'mean'})
authors_mean = authors_mean.reset_index()
authors_mean = authors_mean.rename(columns={'price':'mean_price'})

authors_st = pd.merge(authors_min, authors_max, on = 'author_name', how ='inner')
authors_stat = pd.merge(authors_st, authors_mean, on = 'author_name', how ='inner')

authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000